preloading(
	"awards/Awards_template-01.jpg",
	"awards/ME-Senior-award-2016.png",
	"awards/Awards_template-05.jpg",
	"awards/ME-Professor-award-2016.png",
	"awards/Awards_template-08.jpg",
	"awards/Awards_template-13.jpg",
	"awards/ME-Professor-award-2016.png",
	"awards/IME-Senior-award-2016.png",
	"awards/ME-Senior-award-2016.png",
	"awards/ME-GTA-award-2016.png",
	"awards/IME-GTA-award-2016.png",
	"awards/ME-GRA-award-2016.png",
	"awards/IME-GRA-award-2016.png",
	"awards/Awards_template-04.jpg",
	"awards/Awards_template-13.jpg",
	"IME-Professor-award-2016-01.png"
);