preloading(
	"awards/Awards_template-01.jpg",
	"awards/Awards_template-02.jpg",
	"awards/Awards_template-03.jpg",
	"awards/Awards_template-04.jpg",
	"awards/Awards_template-05.jpg",
	"awards/Awards_template-06.jpg",
	"awards/Awards_template-07.jpg",
	"awards/Awards_template-08.jpg",
	"awards/Awards_template-09.jpg",
	"awards/Awards_template-10.jpg",
	"awards/Awards_template-11.jpg",
	"awards/Awards_template-12.jpg",
	"awards/Awards_template-13.jpg"
);